import { default as Header} from './header';
import {Footer} from './footer';
import {Article} from './article';
import {RecentPosts} from './recent-posts';
import {MostPopular} from './most-popular';
import {Newsletter} from './newsletter';
import {FollowUs} from './follow-us';
import {NewsColumn} from './news-column';
import {Comment} from './comment';
import {CommentForm} from './comment-form';
import {SocialShare} from './social-share';